apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "nodejs-app"
    tags.datadoghq.com/version: "1.1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "nodejs-app"
        tags.datadoghq.com/version: "1.1"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/js-lib.version: "v5.21.0"
    spec:
      containers:
      - name: nodejs-app
        image: datadoguncle.azurecr.io/testdatadog/datadog:newlatest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 90
      targetPort: 3000
